name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build binary
      run: go build -o dummy-server.bin ./cmd

    - name: Run dummy server and test
      run: |
        ./dummy-server.bin &
        sleep 3
        curl http://localhost:8080
        kill $!

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dummy-server
        path: ./dummy-server.bin
